### ISSUE TITLE
关于popup组件的使用问题

### ISSUE THREAD

**Issue by vinceok** [Rychou/mpvue-vant#23]
经过测试发现如下问题；

1. 点击蒙层不能关闭popup
2. close-on-click-overlays属性无效
3. clse回调和close-ovelay回调无效
4. position其实支持center,文档没写
vant自身应该是没有这问题的

**Comment by xxxsimons** [comment]
回调的问题参考README文档，需要手动更改源代码中的监听名为驼峰式。

**Comment by xxxsimons** [comment]
我刚测试是没问题的，你看看应该是你写错了。注意`vue`的语法与小程序是不一样的。

```js
    <van-popup
      :show="show"
      :close-on-click-overlay="true"
      overlay-style="background:red"
      position="top"
      :overlay="true"
      @close="onClose"
    >内容</van-popup>
}
```

**Comment by vinceok** [comment]
再次测试发现，修改了popup/index.js，把this.$emit('click-overlay')改成this.$emit('clickOverlay')后，onClose回调有效，但是点击蒙层仍然不能关闭，于是就只能在onClose里把show改为false

**Comment by xxxsimons** [comment]
> 再次测试发现，修改了popup/index.js，把this.$emit('click-overlay')改成this.$emit('clickOverlay')后，onClose回调有效，但是点击蒙层仍然不能关闭，于是就只能在onClose里把show改为false

试一下拉最新的代码

**Comment by koibi2** [comment]
我刚刚复现了楼主的问题。
1、close-on-click-overlay属性、@clickOverlay方法失效。
2、另外。文档说：bind:close 应该在蒙层关闭时触发。但实际上，点击蒙圈的时候就会触发。

解决方式是：只能在close的方法里设置this.show = false;
原版vant我没用过，猜测小程序版本兼容有问题。

**Comment by leleTang** [comment]
> 我刚刚复现了楼主的问题。
> 1、close-on-click-overlay属性、@clickOverlay方法失效。
> 2、另外。文档说：bind:close 应该在蒙层关闭时触发。但实际上，点击蒙圈的时候就会触发。
> 
> 解决方式是：只能在close的方法里设置this.show = false;
> 原版vant我没用过，猜测小程序版本兼容有问题。

**Comment by leleTang** [comment]
> 我刚刚复现了楼主的问题。
> 1、close-on-click-overlay属性、@clickOverlay方法失效。
> 2、另外。文档说：bind:close 应该在蒙层关闭时触发。但实际上，点击蒙圈的时候就会触发。
> 
> 解决方式是：只能在close的方法里设置this.show = false;
> 原版vant我没用过，猜测小程序版本兼容有问题。

谢谢
