### ISSUE TITLE
mpvue中使用DatetimePicker组件，event.mp.detail这个值并不是实时变化的，是在拖动结束后才有结果，不是边拖动边显示的。。

### ISSUE THREAD

**Issue by Deadpool957** [Rychou/mpvue-vant#30]
楼主有什么解决方案吗

**Comment by Rychou** [comment]
看最下面的`change`事件，https://youzan.github.io/vant-weapp/#/datetime-picker

**Comment by Deadpool957** [comment]
不好意思，我粘错了，不是DatetimePicker这个组件，是slider滑快，event.mp.detail这个值并不是实时变化的，是在拖动结束后才有结果，不是边拖动边显示的

**Comment by Rychou** [comment]
@Deadpool957 刚刚试了一下，的确他组件做的是在滑动结束后才有数据。

如果你想要实时获取的话你可以修改`slider`源代码，更改事件冒泡的时机。

```js
// slider/index.js 74行
      // 注意这里，它是在滑动结束后才emit事件
      if (end) { 
        this.$emit('change', value)
      }
```

只需要把`emit`提取到条件判断外就行了，像这样：
```js
this.$emit('change', value)
//if (end) {  这段代码可以去掉或注释掉
//        this.$emit('change', value)
//}
```

![GIF.gif](https://i.loli.net/2018/12/04/5c06881d7effd.gif)

**Comment by Deadpool957** [comment]
嗯，谢了。我试试
