### ISSUE TITLE
style不生效

### ISSUE THREAD

**Issue by shen-lan** [Rychou/mpvue-vant#31]
按照使用方法dist文件夹内所有复制到static/vant 内
组件应用上了 但是没有任何样式。

**Comment by Rychou** [comment]
@shen-lan 尝试把`dist`文件夹删掉重新跑一次

**Comment by Mr-wang89** [comment]
每一个paga里面都应该放一个main.json

**Comment by Rychou** [comment]
@Mr-wang89 是要放main.json的
