### ISSUE TITLE
collapse折叠事件失效

### ISSUE THREAD

**Issue by cmkwzcs** [Rychou/mpvue-vant#34]
这个bug有解决方案吗？

**Comment by Rychou** [comment]
能详细描述一下嘛？

**Comment by cmkwzcs** [comment]
> 能详细描述一下嘛？

collapse 不是有展开折叠的效果么，这个功能没法用，我这边已经解决了，把vant源码collapse-item组件onclick事件里增加了修改style和class
然后就是现在我已经放弃mpvue了，坑实在是太多了，完全无法用在生产环境，居然所有页面使用同一个data，这个坑开源至今官方都没解决，还是用原生更靠谱。

**Comment by Rychou** [comment]
噢噢 所有页面使用同一个data是啥意思

**Comment by cmkwzcs** [comment]
> 噢噢 所有页面使用同一个data是啥意思
生命周期很坑，页面并不会销毁，data数据不会初始化，需要手动清理，反正挺多坑的，并不适合生产环境开发，数据量大以后性能很差
