### ISSUE TITLE
switch 没有效果

### ISSUE THREAD

**Issue by Sunzhuokai** [Rychou/mpvue-vant#40]
switch 组件可以渲染出来，但是点击后没有任何效果？

**Comment by killkiss** [comment]
不知道这个项目所有组件做测试没有？目前DEMO好像就一个按钮的例子。

**Comment by Rychou** [comment]
10月份的时候全部测试过了 我晚点测一下switch的 一般我使用有问题 我会手动改组件代码

**Comment by Sunzhuokai** [comment]
双向绑定的问题，要在change事件里面赋值

**Comment by Rychou** [comment]
是的 需要手动绑定的
