### ISSUE TITLE
van-tabs组件@click事件捕捉问题

### ISSUE THREAD

**Issue by catfishlty** [Rychou/mpvue-vant#47]
### /static/vant/tabs/index/js line: 121
``` js
// 修改前
this.trigger('click', index);
// 修改后
this.trigger('vclick', index);
```
### test/index.vue
``` html
<van-tabs :active="active" @vclick="handleClick">
```
``` js
handleClick ({ mp }) {
  console.log(mp.detail.index)
}
```

**Comment by Rychou** [comment]
vue和原生小程序的事件捕获机制有啥不一样吗

**Comment by catfishlty** [comment]
> vue和原生小程序的事件捕获机制有啥不一样吗

是mpvue的问题，像click这种原生事件就会捕捉不到detail信息
详见官网：[http://mpvue.com/mpvue/#vue_1](url)

**Comment by Rychou** [comment]
'detail'信息被封装的`e.mp.detail`中去了。这种`vant`组件库用原生写的组件是可以捕获到`click`这种事件的。文档中指的是`vue`组件在引用时无法使用`click`。

**Comment by catfishlty** [comment]
具体的原因我没有去探究，但是使用上确实会发生这样的情况。在隔壁iview那边，用到@click的几个组件也是会受影响的
