### ISSUE TITLE
van-checkbox-group复选框试过么 不显示选择按钮 只显示标题内容

### ISSUE THREAD

**Issue by as236676674** [Rychou/mpvue-vant#48]
求解答 问题出在哪
<van-checkbox-group :value=" result " @change="checkChange">
                <van-checkbox v-for=" (item,index) in list " :key="index" :name=" item " >
                  复选框 {{ item }}
                </van-checkbox>
            </van-checkbox-group>

**Comment by as236676674** [comment]
<van-checkbox-group :value=" result " @change="checkChange">
                <van-checkbox v-for=" (item,index) in list " :key="index" :name=" item " >
                  复选框 {{ item }}
                </van-checkbox>
  </van-checkbox-group>

**Comment by Rychou** [comment]
你好，我刚刚试过了没问题的，请贴上完整的代码

**Comment by as236676674** [comment]
> 你好，我刚刚试过了没问题的，请贴上完整的代码

是我自己得问题，组件名取错了 现在没问题了
